services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: "${SPRING_DATASOURCE_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      POSTGRES_DB: "${SPRING_DATASOURCE_DATABASE}"
    ports:
      - "5432:5432"
    networks:
      - todo_network
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - todo_network
    volumes:
      - todo_redis_data:/data
    environment:
      REDIS_PASSWORD: "${SPRING_REDIS_PASSWORD}"
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${SPRING_DATASOURCE_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-postgres}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"
      SPRING_REDIS_PASSWORD: "${SPRING_REDIS_PASSWORD}"
    ports:
      - "8080:8080"
    networks:
      - todo_network

networks:
  todo_network:

volumes:
  todo_postgres_data:
  todo_redis_data:
